In [1]:
import numpy as np

lol = np.random.random((3,96,96)) #, np.random.random(1)

In [69]:
import torch 

md_logpi = torch.randn((1, 10,5,32))
md_mus = torch.randn((1,10,5,32))
md_sigmas = torch.randn((1,10,5,32))

g_probs = torch.distributions.Categorical(probs=torch.exp(md_logpi.squeeze()).permute(0,2,1))
which_g = g_probs.sample()
print('which g', which_g.shape, md_mus.squeeze().shape)
mus_g, sigs_g = torch.gather(md_mus.squeeze(), 1, which_g.unsqueeze(1)), torch.gather(md_sigmas.squeeze(), 1, which_g.unsqueeze(1))


which g torch.Size([10, 32]) torch.Size([10, 5, 32])


In [15]:
md_logpi.squeeze().permute(0,2,1).shape

torch.Size([10, 32, 5])

In [21]:
lol = torch.randn((4,5,3))
lol

tensor([[[ 0.4226, -0.1532,  0.1831],
         [-1.7333,  0.6322, -1.3454],
         [-0.5202,  0.5227, -0.0040],
         [ 0.2073,  0.0124,  0.4767],
         [ 1.4064, -0.1722, -0.2135]],

        [[ 0.5565,  0.6343,  0.8731],
         [ 0.4362, -0.2045,  1.2388],
         [-0.9787,  0.7820,  0.6471],
         [-0.7562, -0.7615,  0.8965],
         [-1.5286,  1.0121,  2.5571]],

        [[-0.8431, -1.1016, -0.0166],
         [-0.6350, -0.4335,  1.8687],
         [-1.8204,  0.4773,  0.2947],
         [ 0.1919,  3.5515,  0.1440],
         [-0.1534, -0.4970, -0.5794]],

        [[-0.2413, -0.3020,  0.8422],
         [ 0.6990, -1.9366,  0.8286],
         [-0.9251,  0.0673,  0.4389],
         [-0.3918,  0.5636,  0.3824],
         [ 0.1956, -1.2146, -1.1355]]])

In [71]:
g_probs = torch.distributions.Categorical(logits=torch.randn((4,5,3)).permute(0,2,1))
which_g = g_probs.sample()
which_g

tensor([[3, 3, 4],
        [2, 0, 0],
        [3, 1, 0],
        [2, 3, 3]])

In [72]:
which_g.shape

torch.Size([4, 3])

In [73]:
lol.shape

torch.Size([4, 5, 3])

In [74]:
lol

tensor([[[ 0.4226, -0.1532,  0.1831],
         [-1.7333,  0.6322, -1.3454],
         [-0.5202,  0.5227, -0.0040],
         [ 0.2073,  0.0124,  0.4767],
         [ 1.4064, -0.1722, -0.2135]],

        [[ 0.5565,  0.6343,  0.8731],
         [ 0.4362, -0.2045,  1.2388],
         [-0.9787,  0.7820,  0.6471],
         [-0.7562, -0.7615,  0.8965],
         [-1.5286,  1.0121,  2.5571]],

        [[-0.8431, -1.1016, -0.0166],
         [-0.6350, -0.4335,  1.8687],
         [-1.8204,  0.4773,  0.2947],
         [ 0.1919,  3.5515,  0.1440],
         [-0.1534, -0.4970, -0.5794]],

        [[-0.2413, -0.3020,  0.8422],
         [ 0.6990, -1.9366,  0.8286],
         [-0.9251,  0.0673,  0.4389],
         [-0.3918,  0.5636,  0.3824],
         [ 0.1956, -1.2146, -1.1355]]])

In [77]:
torch.gather(lol, 1, which_g.unsqueeze(1)).squeeze().shape

torch.Size([4, 3])

In [57]:
lol[0:2]

tensor([[[ 0.4226, -0.1532,  0.1831],
         [-1.7333,  0.6322, -1.3454],
         [-0.5202,  0.5227, -0.0040],
         [ 0.2073,  0.0124,  0.4767],
         [ 1.4064, -0.1722, -0.2135]],

        [[ 0.5565,  0.6343,  0.8731],
         [ 0.4362, -0.2045,  1.2388],
         [-0.9787,  0.7820,  0.6471],
         [-0.7562, -0.7615,  0.8965],
         [-1.5286,  1.0121,  2.5571]]])

In [58]:
lol[0:2].shape

torch.Size([2, 5, 3])

In [ ]:
1 and 3 did it. 

In [59]:
which_g[0:2]

tensor([[2, 3, 2],
        [0, 4, 0]])

In [60]:
which_g[0:2].shape

torch.Size([2, 3])

In [68]:
torch.gather(lol[0:2], 1, which_g[0:2].unsqueeze(1))

tensor([[[-0.5202,  0.0124, -0.0040]],

        [[ 0.5565,  1.0121,  0.8731]]])

In [5]:
if not [1,2,4]: 
    print('hey')

In [7]:
num_workers = 16
import numpy as np
num_workers- np.floor(num_workers*0.1)

15.0

In [8]:
[1,2][:1]

[1]

In [10]:
import torch
torch.flatten(torch.randn((3,3,9)),end_dim=1).shape

torch.Size([9, 9])

In [2]:
np.random.random(1)

array([0.59519127])

In [3]:
import torch
from torchvision import transforms

In [5]:
torch.distributions.Normal(0.4, 0.02).log_prob(0.4)

tensor(2.9931)

In [12]:
transform = transforms.Compose([
                transforms.ToPILImage(),
                transforms.Resize((64, 64)),
                transforms.ToTensor()
            ])

In [13]:
transform(lol)

TypeError: Input type float64 is not supported